In [11]:
import numpy as np
A = np.linalg.inv(np.matrix("4,7; 5,10"))
B=np.matrix("20; 30")
#C=np.linalg.inv(A)
print(A*B)


[[-2.]
 [ 4.]]


In [12]:
import numpy as np
#A = np.linalg.inv(np.matrix("4,7,-1; -4,2,5; 0,9,4"))
B=np.matrix("7; 3;10")
#C=np.linalg.inv(A)
#print(A*B)

In [13]:
import numpy as np
A=np.matrix("1,1;1,2;1,1")
A_1=np.matrix("1,1,1;1,2,2;1,1,12")
print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(A_1))
#print(round((np.linalg.det(A)),3))

2
3


In [14]:
import numpy as np
A=np.matrix("1,1;1,2;1,1")
A_1=np.matrix("1,1,1;1,2,2;1,1,12")
#A_T=A.T
B=np.matrix("1;2;12")
#A_1=np.matrix("1,1,1;1,2,2;1,1,12")
print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(A_1))
#print(round((np.linalg.det(A)),3))
W=np.linalg.inv(A.T*A)*A.T*B
W

2
3


matrix([[11. ],
        [-4.5]])

Задание 2.9

1 point possible (graded)

Вычислите вектор ошибок  для приближённого решения системы уравнений:

In [15]:
import numpy as np
A_2_9=np.matrix("1,-5;2,1;1,1")
A_1_2_9=np.matrix("1,-5,1;2,1,2;1,1,2")
B_2_9=np.matrix("1;2;2")
C_2_9=np.matrix("1;1")
#print(np.linalg.matrix_rank(A_2_9))
#print(np.linalg.matrix_rank(A_1_2_9))
W_2_9=np.linalg.inv(A_2_9.T*A_2_9)*A_2_9.T*B_2_9
print(A_2_9)
print(W_2_9)
print(W_2_9[0,0])
print(W_2_9[1,0])
e=B_2_9-A_2_9*C_2_9
e



[[ 1 -5]
 [ 2  1]
 [ 1  1]]
[[1.1835443 ]
 [0.05063291]]
1.1835443037974682
0.05063291139240507


matrix([[ 5],
        [-1],
        [ 0]])

Задание 2.11
7 points possible (graded)

In [16]:
import numpy as np
A_2_11=np.matrix("1,2;-3,1;1,2;1,-1")
A_1_2_11=np.matrix("1,2,1;-3,1,4;1,2,5;1,-1,0")
B_2_11=np.matrix("1;4;5;0")
#print(np.linalg.matrix_rank(A_2_9))
#print(np.linalg.matrix_rank(A_1_2_9))
W_2_11=np.linalg.inv(A_2_11.T*A_2_11)*A_2_11.T*B_2_11
#print(A_2_11) 
#print(W_2_11)
#print(W_2_11[0,0])
#print(W_2_11[1,0])
#e=B_2_9-A_2_9*C_2_9
#e
print(A_2_11.T*A_2_11) #1
print(np.linalg.inv(A_2_11.T*A_2_11)) #2
print(A_2_11.T*B_2_11)#3
print(W_2_11)#4

[[12  0]
 [ 0 10]]
[[0.08333333 0.        ]
 [0.         0.1       ]]
[[-6]
 [16]]
[[-0.5]
 [ 1.6]]


In [17]:
import numpy as np # для работы с массивами
import pandas as pd # для работы с DataFrame 
from sklearn import datasets # для импорта данных
import seaborn as sns # для визуализации статистических данных
import matplotlib.pyplot as plt # для построения графиков

column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'PRICE']
boston_data = pd.read_csv('C:\скил\DST-156\IDE_NEW\MATH&ML-2. Линейная алгебра в контексте линейных методов. Часть II/housing.csv', header=None, delimiter=r"\s+", names=column_names)
boston_data.head()


CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  PRICE  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [18]:
# составляем матрицу А и вектор целевой переменной
CRIM = boston_data['CRIM']
RM = boston_data['RM']
A = np.column_stack((np.ones(506), CRIM, RM))
y = boston_data[['PRICE']]
print(A)

[[1.0000e+00 6.3200e-03 6.5750e+00]
 [1.0000e+00 2.7310e-02 6.4210e+00]
 [1.0000e+00 2.7290e-02 7.1850e+00]
 ...
 [1.0000e+00 6.0760e-02 6.9760e+00]
 [1.0000e+00 1.0959e-01 6.7940e+00]
 [1.0000e+00 4.7410e-02 6.0300e+00]]


In [19]:
print(A.shape)

(506, 3)


In [20]:
# вычислим OLS-оценку для коэффициентов
w_hat = np.linalg.inv(A.T@A)@A.T@y
print(w_hat.values)

[[-29.24471945]
 [ -0.26491325]
 [  8.39106825]]


In [21]:
# добавились новые данные:
CRIM_new = 0.1
RM_new = 8
# делаем прогноз типичной стоимости дома
PRICE_new = w_hat.iloc[0]+w_hat.iloc[1]*CRIM_new+w_hat.iloc[2]*RM_new
print(PRICE_new.values)
## [37.85733519]

[37.85733519]


In [22]:
# короткий способ сделать прогноз
new=np.array([[1,CRIM_new,RM_new]])
print('prediction:', (new@w_hat).values)
## prediction: [[37.85733519]]

prediction: [[37.85733519]]


In [23]:
from sklearn.linear_model import LinearRegression
# создаём модель линейной регрессии
model = LinearRegression(fit_intercept=False)
# вычисляем коэффициенты регрессии
model.fit(A, y)
print('w_hat:', model.coef_)
new_prediction = model.predict(new)
print('prediction:', new_prediction)
## w_hat: [[-29.24471945  -0.26491325   8.39106825]]
## prediction: [[37.85733519]]

w_hat: [[-29.24471945  -0.26491325   8.39106825]]
prediction: [[37.85733519]]


Задание 3.5

1 point possible (graded)

Сделайте прогноз типичной стоимости (в тыс. долларов) дома в городе с уровнем преступности  и средним количеством комнат в доме . В качестве модели используйте линейную регрессию, оценка вектора коэффициентов которой равна:

Ответ округлите до целого числа.

In [24]:
# добавились новые данные:
CRIM_new_3_5 = 0.2
RM_new_3_5 = 6
# делаем прогноз типичной стоимости дома
PRICE_new_3_5 = w_hat.iloc[0]+w_hat.iloc[1]*CRIM_new_3_5+w_hat.iloc[2]*RM_new_3_5
print(PRICE_new_3_5.values)


[21.04870738]


In [25]:
CRIM_new_3_5 = 0.2
RM_new_3_5 = 6
# короткий способ сделать прогноз
new_3_5=np.array([[1,CRIM_new_3_5,RM_new_3_5]])
#print('prediction:', (new@w_hat).values)
## prediction: [[37.85733519]]
from sklearn.linear_model import LinearRegression
# создаём модель линейной регрессии
model = LinearRegression(fit_intercept=False)
# вычисляем коэффициенты регрессии
model.fit(A, y)
print('w_hat:', model.coef_)
new_prediction_3_5 = model.predict(new_3_5)
print('prediction:', new_prediction_3_5)

w_hat: [[-29.24471945  -0.26491325   8.39106825]]
prediction: [[21.04870738]]


In [26]:
import numpy as np
AAA= np.matrix(" 1,2,-2 ; 1,1,-1 ; 1,1,-1 ;1,2,-2 ")
print(np.linalg.det(AAA.T@AAA))

0.0


In [27]:
# создадим вырожденную матрицу А
AA = np.array([
    [1, 1, 1, 1], 
    [2, 1, 1, 2], 
    [-2, -1, -1, -2]]
).T
y = np.array([1, 2, 5, 1])
print(np.linalg.det(AA.T@AA))

# вычислим OLS-оценку для коэффициентов
#w_hat=np.linalg.inv(A.T@A)@A.T@y
#print(w_hat) 
## LinAlgError: Singular matrix

0.0


In [28]:
# создаём модель линейной регрессии
model = LinearRegression(fit_intercept=False)
# вычисляем коэффициенты регрессии
model.fit(A, y)
print('w_hat:', model.coef_)
## w_hat: [ 6.   -1.25  1.25]

ValueError: Found input variables with inconsistent numbers of samples: [506, 4]

In [89]:
np.linalg.lstsq(A, y, rcond=None)

(array([ 6.  , -1.25,  1.25]),
 array([], dtype=float64),
 2,
 array([4.86435029, 0.58146041, 0.        ]))

In [91]:
A_3_7 = np.array([
    [1, -1, 0], 
    [1, 1, 2], 
    [0, 0, 0],
    [2,0,2]]
)
y = np.array([1, 2, 1, 2])
print(np.linalg.det(A_3_7.T@A_3_7))

0.0


In [92]:
boston_data[['CHAS', 'LSTAT', 'CRIM','RM']].describe()

CHAS       LSTAT        CRIM          RM
count  506.000000  506.000000  506.000000  506.000000
mean     0.069170   12.653063    3.613524    6.284634
std      0.253994    7.141062    8.601545    0.702617
min      0.000000    1.730000    0.006320    3.561000
25%      0.000000    6.950000    0.082045    5.885500
50%      0.000000   11.360000    0.256510    6.208500
75%      0.000000   16.955000    3.677083    6.623500
max      1.000000   37.970000   88.976200    8.780000

In [93]:
# составляем матрицу наблюдений и вектор целевой переменной
A = np.column_stack((np.ones(506), boston_data[['CHAS', 'LSTAT', 'CRIM','RM']]))
y = boston_data[['PRICE']]
# вычисляем OLS-оценку для коэффициентов без стандартизации
w_hat=np.linalg.inv(A.T@A)@A.T@y
print(w_hat.values)

[[-1.92052548]
 [ 3.9975594 ]
 [-0.58240212]
 [-0.09739445]
 [ 5.07554248]]


In [94]:
# составляем матрицу наблюдений без дополнительного столбца из единиц
A = boston_data[['CHAS', 'LSTAT', 'CRIM','RM']]
y = boston_data[['PRICE']]
# стандартизируем векторы в столбцах матрицы A
A_cent = A - A.mean(axis=0)
A_st = A_cent/np.linalg.norm(A_cent, axis=0)
A_st.describe().round(2)

CHAS   LSTAT    CRIM      RM
count  506.00  506.00  506.00  506.00
mean    -0.00   -0.00   -0.00   -0.00
std      0.04    0.04    0.04    0.04
min     -0.01   -0.07   -0.02   -0.17
25%     -0.01   -0.04   -0.02   -0.03
50%     -0.01   -0.01   -0.02   -0.00
75%     -0.01    0.03    0.00    0.02
max      0.16    0.16    0.44    0.16

In [95]:
print(np.linalg.norm(A_st, axis=0))
## [1. 1. 1. 1.]

[1. 1. 1. 1.]


In [96]:
# стандартизируем вектор целевой переменной
y_cent = y - y.mean()
y_st = y_cent/np.linalg.norm(y_cent)

In [97]:
# вычислим OLS-оценку для стандартизированных коэффициентов
w_hat_st=np.linalg.inv(A_st.T@A_st)@A_st.T@y_st
print(w_hat_st.values)

[[ 0.11039956]
 [-0.45220423]
 [-0.09108766]
 [ 0.38774848]]


In [98]:
A_st.T @ A_st

CHAS     LSTAT      CRIM        RM
CHAS   1.000000 -0.053929 -0.055892  0.091251
LSTAT -0.053929  1.000000  0.455621 -0.613808
CRIM  -0.055892  0.455621  1.000000 -0.219247
RM     0.091251 -0.613808 -0.219247  1.000000

In [107]:
A_4_3=np.array([12, 8])
A_cent_4_3 = A_4_3 - A_4_3.mean(axis=0)
A_st_4_3 = A_cent_4_3/np.linalg.norm(A_cent_4_3, axis=0)
A_st_4_3
print(round((A_st_4_3[0]),3))
print(round((A_st_4_3[1]),3))
A_st_4_3

0.707
-0.707


array([ 0.70710678, -0.70710678])

In [108]:
x_1 = np.array([1, 2, 6])
x_2 = np.array([3000, 1000, 2000])
np.corrcoef(x_1, x_2)

array([[ 1.        , -0.18898224],
       [-0.18898224,  1.        ]])

Задание 4.7

1 point possible (graded)

Вычислите коэффициент корреляции между векторами  и .

Ответ округлите до двух знаков после точки-разделителя.

In [114]:
x_1 = np.array([5, 1, 2])
x_2 = np.array([4,2, 8])
np.corrcoef(x_1, x_2)

array([[1.        , 0.05241424],
       [0.05241424, 1.        ]])

Задание 4.8

3 points possible (graded)

Составьте корреляционную матрицу для системы векторов:

Для расчёта используйте библиотеку NumPy или Pandas.

1. Чему равен ранг полученной корреляционной матрицы?

In [123]:
x_1_4_8= np.array([5.1, 1.8, 2.1 ,10.3, 12.1, 12.6])
x_2_4_8 = np.array([10.2, 3.7, 4.1, 20.5, 24.2, 24.1])
x_3_4_8 = np.array([2.5, 0.9, 1.1, 5.1, 6.1, 6.3])
X_4_8=np.corrcoef([x_1_4_8, x_2_4_8, x_3_4_8])
print(np.linalg.matrix_rank(X_4_8))
print('Determinant: {:.7f}'.format(np.linalg.det(X_4_8)))
print(X_4_8)


3
Determinant: 0.0000005
[[1.         0.99925473 0.99983661]
 [0.99925473 1.         0.99906626]
 [0.99983661 0.99906626 1.        ]]


In [1]:
import numpy as np
A=np.matrix("1,1,1;1,3,9;1,-2,4;1,1,1")
A_1=np.matrix("1,1,1,4;1,3,9,5;1,-2,4,2;1,1,1,2")
print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(A_1))
#print(round((np.linalg.det(A)),3))

3
4


In [8]:
y = np.array([4, 5, 2, 2])
w_hat = np.linalg.inv(A.T@A)@A.T@y
print(w_hat) 

[[2.4        0.46666667 0.13333333]]


In [29]:
import numpy as np
A=np.matrix("1,1,3,1,3,9;1,3, 4, 9, 12, 16;1,-2, 5, 4, -10, 25;1,1,-2, 1, -2, 4;1,5, 4, 25, 20, 16;1,13, 11, 169, 143, 121;1,1, 3, 1, 3, 9")
A_1=np.matrix("1,1,3,1,3,9,4;1,3, 4, 9, 12, 16, 5;1,-2, 5, 4, -10, 25, 2;1,1,-2, 1, -2, 4, 2;1,5, 4, 25, 20, 16, 6;1,13, 11, 169, 143, 121, 8;1,1, 3, 1, 3, 9, -1")
print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(A_1))
#print(round((np.linalg.det(A)),3))
y = np.array([4, 5, 2, 2,6,8,-1])
w_hat = np.linalg.inv(A.T@A)@A.T@y
print(w_hat) 

6
7
[[-2.25799015  2.37672337 -0.1322068  -0.10208147 -0.26501791  0.29722471]]


In [32]:
A = np.array([
    [1, 3, -2, 1, 5, 13, 1],
    [3, 4, 5, -2, 4, 11, 3],
    [4, 5, 2, 2, 6, 8, -1],
]).T
#print(A)
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2, include_bias=True)
A_poly = poly.fit_transform(A)
display(pd.DataFrame(A_poly))

0     1     2    3      4      5      6      7     8     9
0  1.0   1.0   3.0  4.0    1.0    3.0    4.0    9.0  12.0  16.0
1  1.0   3.0   4.0  5.0    9.0   12.0   15.0   16.0  20.0  25.0
2  1.0  -2.0   5.0  2.0    4.0  -10.0   -4.0   25.0  10.0   4.0
3  1.0   1.0  -2.0  2.0    1.0   -2.0    2.0    4.0  -4.0   4.0
4  1.0   5.0   4.0  6.0   25.0   20.0   30.0   16.0  24.0  36.0
5  1.0  13.0  11.0  8.0  169.0  143.0  104.0  121.0  88.0  64.0
6  1.0   1.0   3.0 -1.0    1.0    3.0   -1.0    9.0  -3.0   1.0

In [33]:
def polynomial_regression(X, y, k):
    poly = PolynomialFeatures(degree=k, include_bias=True)
    X_poly = poly.fit_transform(X)
    w_hat = np.linalg.inv(X_poly.T@X_poly)@X_poly.T@y
    y_pred = X_poly @ w_hat
    return X_poly, y_pred, w_hat

In [34]:
A = boston_data[['LSTAT', 'PTRATIO', 'RM', 'CRIM']]
y = boston_data[['PRICE']]
 
A_poly, y_pred, w_hat = polynomial_regression(A, y, 1)
A_poly2, y_pred2, w_hat2 = polynomial_regression(A, y, 2)
A_poly3, y_pred3, w_hat3 = polynomial_regression(A, y, 3)
A_poly4, y_pred4, w_hat4 = polynomial_regression(A, y, 4)
A_poly5, y_pred5, w_hat5 = polynomial_regression(A, y, 5)

In [35]:
from sklearn.metrics import mean_absolute_percentage_error
 
print('MAPE для полинома 1-й степени {:.2f}%'.format(mean_absolute_percentage_error(y, y_pred)*100))
print('MAPE для полинома 2-й степени  {:.2f}%'.format(mean_absolute_percentage_error(y, y_pred2)*100))
print('MAPE для полинома 3-й степени  {:.2f}%'.format(mean_absolute_percentage_error(y, y_pred3)*100))
print('MAPE для полинома 4-й степени  {:.2f}%'.format(mean_absolute_percentage_error(y, y_pred4)*100))
print('MAPE для полинома 5-й степени  {:.2f}%'.format(mean_absolute_percentage_error(y, y_pred5)*100))
## MAPE для полинома 1-й степени 18.20%
## MAPE для полинома 2-й степени 13.41%
## MAPE для полинома 3-й степени 12.93%
## MAPE для полинома 4-й степени 10.74%
## MAPE для полинома 5-й степени 70.18%

MAPE для полинома 1-й степени 18.20%
MAPE для полинома 2-й степени  13.41%
MAPE для полинома 3-й степени  12.93%
MAPE для полинома 4-й степени  10.75%
MAPE для полинома 5-й степени  250.48%


In [36]:
display(pd.DataFrame(w_hat5).describe())

PRICE
count     126.000000
mean      925.086928
std     25153.258366
min   -120077.707584
25%        -0.492863
50%        -0.000022
75%         2.049684
max    250983.366126

In [37]:
# считаем матрицу корреляций (без столбца из единиц)
C = pd.DataFrame(A_poly5[:, 1:]).corr()
# считаем ранг корреляционной матрицы
print('Ранг корреляционной матрицы:', np.linalg.matrix_rank(C))
# считаем количество факторов (не включая столбец из единиц)
print('Количество факторов:', A_poly5[:, 1:].shape[1])
# Ранг корреляционной матрицы: 110
# Количество факторов: 125

Ранг корреляционной матрицы: 110
Количество факторов: 125


In [38]:
display(pd.DataFrame(w_hat4).describe())

PRICE
count    70.000000
mean    -50.932531
std     887.744200
min   -6928.814677
25%      -0.187950
50%      -0.000813
75%       0.322197
max    2305.449752

In [39]:
def polynomial_regression_sk(X, y, k):
    poly = PolynomialFeatures(degree=k, include_bias=False)
    X_poly = poly.fit_transform(X)
    lr = LinearRegression().fit(X_poly, y)
    y_pred = lr.predict(X_poly)
    return X_poly, y_pred, lr.coef_

A = boston_data[['LSTAT', 'PTRATIO', 'RM', 'CRIM']]
y = boston_data[['PRICE']]

for k in range(1, 6):
    A_poly, y_pred, w_hat = polynomial_regression_sk(A, y, k)
    print(
        "MAPE для полинома степени {} — {:.2f}%, СКО — {:.0f}".format(
            k, mean_absolute_percentage_error(y, y_pred)*100, w_hat.std()
        )

    )
## MAPE для полинома степени 1 — 18.20%, СКО — 2
## MAPE для полинома степени 2 — 13.41%, СКО — 5
## MAPE для полинома степени 3 — 12.93%, СКО — 9
## MAPE для полинома степени 4 — 10.74%, СКО — 304
## MAPE для полинома степени 5 — 9.02%, СКО — 17055

MAPE для полинома степени 1 — 18.20%, СКО — 2
MAPE для полинома степени 2 — 13.41%, СКО — 5
MAPE для полинома степени 3 — 12.93%, СКО — 9
MAPE для полинома степени 4 — 10.74%, СКО — 304
MAPE для полинома степени 5 — 9.03%, СКО — 17055


Задание 6.4

3 points possible (graded)

С помощью классического МНК найдите коэффициенты полиномиальной регрессии, если используется полином второй степени и задан фактор  и целевая переменная .

В качестве ответа приведите координаты вектора коэффициентов , , , округлив их до первого знака после точки-разделителя.

In [41]:
import numpy as np
A_6_4=np.matrix("1,1,1;1,3,9;1,-2,4;1,9,81")
#A_1=np.matrix("1,1,3,1,3,9,4;1,3, 4, 9, 12, 16, 5;1,-2, 5, 4, -10, 25, 2;1,1,-2, 1, -2, 4, 2;1,5, 4, 25, 20, 16, 6;1,13, 11, 169, 143, 121, 8;1,1, 3, 1, 3, 9, -1")
#print(np.linalg.matrix_rank(A))
#print(np.linalg.matrix_rank(A_1))
#print(round((np.linalg.det(A)),3))
y_6_4 = np.array([3, 7, -5, 21])
w_hat_6_4 = np.linalg.inv(A_6_4.T@A_6_4)@A_6_4.T@y_6_4
print(w_hat_6_4) 

[[ 0.11446013  2.46095638 -0.01608801]]


In [48]:
from sklearn.model_selection import cross_validate
# выделяем интересующие нас факторы
X = boston_data[['LSTAT', 'PTRATIO', 'RM','CRIM']]
y = boston_data[['PRICE']]
 
# добавляем полиномиальные признаки
poly = PolynomialFeatures(degree=3, include_bias=False)
X = poly.fit_transform(X)
 
# создаём модель линейной регрессии
lr = LinearRegression()
 
# оцениваем качество модели на кросс-валидации, метрика — MAPE
cv_results = cross_validate(lr, X, y, scoring='neg_mean_absolute_percentage_error', cv=5, return_train_score=True)
print('MAPE на тренировочных фолдах: {:.2f} %'.format(-cv_results['train_score'].mean()* 100))
print('MAPE на валидационных фолдах: {:.2f} %'.format(-cv_results['test_score'].mean() * 100))	
 
## MAPE на тренировочных фолдах: 12.64 %
## MAPE на валидационных фолдах: 24.16 %

MAPE на тренировочных фолдах: 12.64 %
MAPE на валидационных фолдах: 24.16 %


In [51]:
# матрица наблюдений (включая столбец единиц)
A = np.array([
    [1, 1, 1, 1, 1],
    [1, 0, -3, 2, 4],
    [2, 0, -6, 4, 8]
]).T
# вектор целевого признака
y = np.array([4, 3, -4, 2, 7])
print(A)
print(A.T)
# получаем оценку коэффициентов регрессии по МНК
#w_hat = np.linalg.inv(A.T@A)@A.T@y
#print(w_hat) 
## LinAlgError: Singular matrix

[[ 1  1  2]
 [ 1  0  0]
 [ 1 -3 -6]
 [ 1  2  4]
 [ 1  4  8]]
[[ 1  1  1  1  1]
 [ 1  0 -3  2  4]
 [ 2  0 -6  4  8]]


In [54]:
# матрица наблюдений (включая столбец единиц)
A = np.array([
    [1, 1, 1, 1, 1],
    [1, 0, -3, 2, 4],
    [2, 0, -6, 4, 8]
]).T
# вектор целевого признака
y = np.array([4, 3, -4, 2, 7])
# единичная матрица
E = np.eye(3)
 
# коэффициент регуляризации 
alpha = 5
print(E*alpha)
# получаем оценку коэффициентов регрессии по МНК с регуляризацией Тихонова
w_hat_ridge = np.linalg.inv(A.T@A+alpha*E)@A.T@y
print(w_hat_ridge) 
## [0.6122449  0.29387755 0.5877551 ]

[[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]]
[0.6122449  0.29387755 0.5877551 ]


In [56]:
from sklearn.linear_model import Ridge
# матрица наблюдений (включая столбец единиц)
A = np.array([
    [1, 1, 1, 1, 1],
    [1, 0, -3, 2, 4],
    [2, 0, -6, 4, 8]
]).T
# вектор целевого признака
y = np.array([4, 3, -4, 2, 7])
# получаем оценку коэффициентов регрессии по МНК с регуляризацией Тихонова
ridge = Ridge(alpha=5, fit_intercept=False)
ridge.fit(A, y)
print(ridge.coef_) 
## [0.6122449  0.29387755 0.5877551 ]

[0.6122449  0.29387755 0.5877551 ]


In [62]:
from sklearn.preprocessing import StandardScaler
# выделяем интересующие нас факторы
X = boston_data[['LSTAT', 'PTRATIO', 'RM','CRIM']]
y = boston_data[['PRICE']]
# инициализируем стандартизатор StandardScaler
scaler = StandardScaler()
# подгоняем параметры стандартизатора (вычисляем среднее и СКО)
X = scaler.fit_transform(X)
# добавляем полиномиальные признаки
poly = PolynomialFeatures(degree=3, include_bias=False)
X = poly.fit_transform(X)
# создаём модель линейной регрессии c L2-регуляризацией
ridge = Ridge(alpha=20, solver='svd')
# оцениваем качество модели на кросс-валидации
cv_results = cross_validate(ridge, X, y, scoring='neg_mean_absolute_percentage_error', cv=5, return_train_score=True)
print('MAPE на тренировочных фолдах: {:.2f} %'.format(-cv_results['train_score'].mean()* 100))
print('MAPE на валидационных фолдах: {:.2f} %'.format(-cv_results['test_score'].mean() * 100))
## MAPE на тренировочных фолдах: 12.54 %
## MAPE на валидационных фолдах: 17.02 %

MAPE на тренировочных фолдах: 12.54 %
MAPE на валидационных фолдах: 17.02 %


Задание 7.4

4 points possible (graded)

Вычислите коэффициенты линейной регрессии с -регуляризацией, используя аналитическую формулу Тихонова, если:

и
Коэффициент регуляризации .

В качестве ответа приведите значения полученных коэффициентов линейной регрессии, округлив их до второго знака после точки-разделителя.

In [67]:
from sklearn.linear_model import Ridge
# матрица наблюдений (включая столбец единиц)
A_7_4 = np.array([
    [1, 1, 1, 1, 1],
    [5, 9, 4, 3, 5],
    [15, 18, 18, 19, 19],
    [7, 6, 7, 7, 7]
]).T
# вектор целевого признака
y_7_4 = np.array([24, 22, 35, 33, 36])
# получаем оценку коэффициентов регрессии по МНК с регуляризацией Тихонова
ridge_7_4 = Ridge(alpha=1, fit_intercept=False)
ridge_7_4.fit(A_7_4, y_7_4)
print(ridge_7_4.coef_)
## [0.6122449  0.29387755 0.5877551 ]

[-0.08523045 -1.70784126  1.91141216  0.7293992 ]


In [76]:
from sklearn.linear_model import Lasso
# матрица наблюдений (включая столбец единиц)
A = np.array([
    [1, 1, 1, 1, 1],
    [1, 0, -3, 2, 4],
    [2, 0, -6, 4, 8]
]).T
# вектор целевого признака
y = np.array([4, 3, -4, 2, 7])
# получаем оценку коэффициентов регрессии с помощью L1-регуляризации
lasso = Lasso(alpha=0.1, fit_intercept=False)
lasso.fit(A, y)
print(lasso.coef_)
## [1.14925373 0.         0.71921642]

[1.14925373 0.         0.71921642]


In [79]:
# выделяем интересующие нас факторы
X = boston_data[['LSTAT', 'PTRATIO', 'RM','CRIM']]
y = boston_data[['PRICE']]

# инициализируем стандартизатор StandardScaler
scaler = StandardScaler()
# подгоняем параметры стандартизатора (вычисляем среднее и СКО)
X = scaler.fit_transform(X)

# добавляем полиномиальные признаки
poly = PolynomialFeatures(degree=3, include_bias=False)
X = poly.fit_transform(X)

# создаём модель линейной регрессии c L1-регуляризацией
lasso = Lasso(alpha=0.1, max_iter=10000)

# оцениваем качество модели на кросс-валидации
cv_results = cross_validate(lasso, X, y, scoring='neg_mean_absolute_percentage_error', cv=5, return_train_score=True)
print('MAPE на тренировочных фолдах: {:.2f} %'.format(-cv_results['train_score'].mean()* 100))
print('MAPE на валидационных фолдах: {:.2f} %'.format(-cv_results['test_score'].mean() * 100))
## MAPE на тренировочных фолдах: 12.44 %
## MAPE на валидационных фолдах: 16.44 %

MAPE на тренировочных фолдах: 12.44 %
MAPE на валидационных фолдах: 16.44 %


In [80]:
from sklearn.linear_model import ElasticNet

In [81]:
# матрица наблюдений (включая столбец единиц)
A = np.array([
    [1, 1, 1, 1, 1],
    [1, 0, -3, 2, 4],
    [2, 0, -6, 4, 8]
]).T
# вектор целевого признака
y = np.array([4, 3, -4, 2, 7])
# получаем оценку коэффициентов регрессии 
elasticnet = ElasticNet(alpha=0.1, l1_ratio=0.2, fit_intercept=False)
elasticnet.fit(A, y)
print(elasticnet.coef_)
## [1.13492457 0.19525842 0.6237965 ]

[1.13492457 0.19525842 0.6237965 ]


In [82]:
# получаем оценку коэффициентов регрессии
elasticnet = ElasticNet(alpha=0.1, l1_ratio=0.7, fit_intercept=False)
elasticnet.fit(A, y)
print(elasticnet.coef_)
## [1.14379753 0.         0.71993025]

[1.14379753 0.         0.71993025]


In [83]:
# получаем оценку коэффициентов регрессии
elasticnet = ElasticNet(alpha=0.1, l1_ratio=1, fit_intercept=False)
elasticnet.fit(A, y)
print(elasticnet.coef_)
## [1.14925373 0.         0.71921642]

[1.14925373 0.         0.71921642]


In [84]:
# выделяем интересующие нас факторы
X = boston_data[['LSTAT', 'PTRATIO', 'RM','CRIM']]
y = boston_data[['PRICE']]
# инициализируем стандартизатор StandardScaler
scaler = StandardScaler()
# подгоняем параметры стандартизатора (вычисляем среднее и СКО)
X = scaler.fit_transform(X)
# добавляем полиномиальные признаки
poly = PolynomialFeatures(degree=3, include_bias=False)
X = poly.fit_transform(X)
# создаём модель линейной регрессии c L1- и L2-регуляризациями
lasso = ElasticNet(alpha=0.1, l1_ratio=0.5, max_iter=10000)
# оцениваем качество модели на кросс-валидации
cv_results = cross_validate(lasso, X, y, scoring='neg_mean_absolute_percentage_error', cv=5, return_train_score=True)
print('MAPE на тренировочных фолдах: {:.2f} %'.format(-cv_results['train_score'].mean()* 100))
print('MAPE на валидационных фолдах: {:.2f} %'.format(-cv_results['test_score'].mean() * 100)) 
## MAPE на тренировочных фолдах: 12.65 %
## MAPE на валидационных фолдах: 15.70 %

MAPE на тренировочных фолдах: 12.65 %
MAPE на валидационных фолдах: 15.70 %
