In [1]:
import pandas as pd

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})
Hut_Paradise_DF

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

Задание 3.3

1/1 point (graded)

Найдите вектор параметров квартиры номер 5 (нумерация квартир — с 1). Для преобразования DataFrame в массив numpy можно воспользоваться атрибутом values:

Hut_Paradise_values = Hut_Paradise_DF.values
  
Выберите координаты данного вектора:

In [2]:
Hut_Paradise_values = Hut_Paradise_DF.values

In [3]:
x_3_3=Hut_Paradise_values[4] # вторая строка матрицы А
print('Вектор параметров квартиры номер 5:\n',x_3_3)
print('type of x_3_3:',type(x_3_3))

Вектор параметров квартиры номер 5:
 [40 33  1  6 20 16]
type of x_3_3: <class 'numpy.ndarray'>


Задание 3.4

1/1 point (graded)

Найдите вектор этажей всех квартир. Выберите координаты полученного вектора:

In [4]:
y_3_4=Hut_Paradise_values[:,3] # четвертый столбец матрицы А
print('Вектор этажей всех квартир:\n',y_3_4)

Вектор этажей всех квартир:
 [ 5 12 10  3  6 13  8 21  5]


Задание 3.5

1 point possible (graded)

Вычислите вектор нежилой площади. Выберите координаты полученного вектора:

In [5]:
#Area=Hut_Paradise_values[:,1] 
#Liv_Area= Hut_Paradise_values[:,5]
Non_liv_area=Hut_Paradise_values[:,1]-Hut_Paradise_values[:,5]
print('Вектор нежилой площади:\n',Non_liv_area)


Вектор нежилой площади:
 [13 12 15 13 17  9 20 15 25]


Задание 3.6

1 point possible (graded)

Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, в третьей — полчаса, в четверой — 15 минут, в пятой — 5 минут, в шестой — 40 минут, в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут.

Найдите продолжительность просмотров в минутах во всех квартирах за две недели.

In [6]:
import numpy as np
Viewing_duration=np.array([10,20,30,15,5,40,20,8,20])
s_3_6=np.dot(Viewing_duration,Hut_Paradise_values[:,4])
print('scalar product:',s_3_6)


scalar product: 1348


Задание 3.7

1 point possible (graded)

Составьте линейную комбинацию векторов  и  с коэффициентами 2 и -3. Выберите координаты полученного вектора:

In [7]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])


d_3_7=2*v-3*w
print('linear combination:',d_3_7)

linear combination: [-3 14  3  4  2]


Задание 3.8

1 point possible (graded)

Будет ли эта комбинация ортогональна вектору ?

In [8]:
s_3_8=np.dot(d_3_7,u)
print('scalar product:',s_3_8)

scalar product: 0


In [9]:
A = np.matrix([
    [1, -5, 3], 
    [2, 2, 1],
    [0, 3, 1],
    [2, 4, 12]
])
A
A.shape
print('a_23=', A[1, 2], 'a_32=', A[2, 1], 'a_33=', A[2,2])

a_23= 1 a_32= 3 a_33= 1


In [10]:
A = np.array([
    [1, -5, 3], 
    [2, 2, 1],
    [0, 3, 1],
    [2, 4, 12]
])
A

array([[ 1, -5,  3],
       [ 2,  2,  1],
       [ 0,  3,  1],
       [ 2,  4, 12]])

In [11]:
A = np.matrix("1, -5; 2, 2; 0, 3")
B = np.matrix("3, 1, 0; -1, 0, 2")

In [12]:
A

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [13]:
B

matrix([[ 3,  1,  0],
        [-1,  0,  2]])

In [14]:
C_1=np.dot(A,B)
print(C_1)
print(C_1.shape)


[[  8   1 -10]
 [  4   2   4]
 [ -3   0   6]]
(3, 3)


In [15]:
C_2=np.dot(B,A)
print(C_2)
print(C_2.shape)


[[  5 -13]
 [ -1  11]]
(2, 2)


In [16]:
A_1 = np.matrix("2,3; 1,3")
B_1 = np.matrix("4,1; 1,0")
print(A_1)
print(B_1)

[[2 3]
 [1 3]]
[[4 1]
 [1 0]]


In [17]:
C_3=np.dot(A_1,B_1)
C_4=np.dot(B_1,A_1)
print(C_3,C_3.shape)
print("__________")
print(C_4,C_4.shape)



[[11  2]
 [ 7  1]] (2, 2)
__________
[[ 9 15]
 [ 2  3]] (2, 2)


In [18]:
A_2 = np.matrix("1,2,3; 4,1,1 ; 0,2,1")
B_2 = np.matrix("1; 2; -1")
print(A_2)
print(B_2)

[[1 2 3]
 [4 1 1]
 [0 2 1]]
[[ 1]
 [ 2]
 [-1]]


In [19]:
C_5=np.dot(A_2,B_2)
#C_6=np.dot(B_2,A_2)
print(C_5,C_5.shape)
print("__________")
#print(C_5,C_6.shape)

[[2]
 [5]
 [3]] (3, 1)
__________


In [20]:
A_3 = np.matrix("1,2,3; 4,1,1 ; 0,2,1")
B_3 = np.matrix("1, 2, -1")
print(A_3)
print(B_3)

[[1 2 3]
 [4 1 1]
 [0 2 1]]
[[ 1  2 -1]]


In [21]:
#C_7=np.dot(A_3,B_3)
C_8=np.dot(B_3,A_3)
#print(C_7,C_7.shape)
print("__________")
print(C_8,C_8.shape)

__________
[[9 2 4]] (1, 3)


In [22]:
A_4 = np.matrix("1; 2 ; 3")
B_4 = np.matrix("4; 5 ; 6").T
print(A_4)
print(B_4)

[[1]
 [2]
 [3]]
[[4 5 6]]


In [23]:
C_9=np.dot(A_4,B_4)
C_10=np.dot(B_4,A_4)
print(C_9,C_9.shape)
print("__________")
print(C_10,C_10.shape)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]] (3, 3)
__________
[[32]] (1, 1)


In [24]:
C_11=np.dot(A_4,B_4)

print(C_11)


[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


Задание 6.3

2 points possible (graded)

In [25]:
A_6_3 = np.matrix("1,-1,2,4,0; 8,2,0,5,3 ; 0,1,2,1,2")
B_6_3 = np.matrix("1,0,1,0; 0,0,2,-1; 1,0,1,1; 0,1,1,1; 1,1,0,-1")
#print(A_6_3)

#print(B_6_3)

C=np.dot(A_6_3,B_6_3)
print(C[0,1],C[2,3])

4 0


Задание 6.4

1 point possible (graded)

Матрица какого размера получится, если умножить матрицу  на матрицу ?

In [26]:
A_6_4 = np.matrix("1,2,1; 4,4,4")
B_6_4 = np.matrix("1,0,6,1; 0,1,0,1; 6,0,1,1")
#print(A_6_3)

#print(B_6_3)

C=np.dot(A_6_4,B_6_4)
print(C.shape)

(2, 4)


Задание 6.5

4 points possible (graded)

Найдите тензорное произведение векторо

In [27]:
A_6_5 = np.matrix("1; 3")
B_6_5 = np.matrix("-3; 1").T
#print(A_6_5)
#print(B_6_5)
C_6_5=np.dot(A_6_5,B_6_5)
C_6_5

matrix([[-3,  1],
        [-9,  3]])

In [28]:
A_21 = np.matrix("1,2,3; 4,1,1;0,2,1")
B_21 = np.matrix("1,0,0; 0,2,0;0,0,3")
print(A_21)
print(B_21)
C_21_1=np.dot(A_21,B_21)
C_21_2=np.dot(B_21,A_21)
print('************')
print(C_21_1)
print('_________')
print(C_21_2)

[[1 2 3]
 [4 1 1]
 [0 2 1]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
************
[[1 4 9]
 [4 2 3]
 [0 4 3]]
_________
[[1 2 3]
 [8 2 2]
 [0 6 3]]


Задание 6.7

4 points possible (graded)

In [29]:
A_6_7 = np.matrix("2,0; 0,2")
B_6_7 = np.matrix("1,1; 4,5")
C_6_7=np.dot(A_6_7,B_6_7)
C_6_7


matrix([[ 2,  2],
        [ 8, 10]])

Задание 6.9

1 point possible (graded)

Составьте матрицу  из системы векторов:

Найдите матрицу Грама .

Выберите верный вариант ответа:

In [30]:
A_6_9 = np.matrix("1,1; 2,-1; 1,2").T
A_6_9_1=A_6_9.T
G=np.dot(A_6_9_1,A_6_9)
G


matrix([[2, 1, 3],
        [1, 5, 0],
        [3, 0, 5]])

In [35]:
A = np.matrix('1,2,3,4; 4,5,6,5; 7,8,10,11; 12,13,14,15')
A
B=np.linalg.inv(A)
B
C=A*B
C

matrix([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         -2.22044605e-16],
        [-1.33226763e-15,  1.00000000e+00,  0.00000000e+00,
          2.22044605e-16],
        [-3.99680289e-15,  8.88178420e-16,  1.00000000e+00,
         -6.66133815e-16],
        [-8.88178420e-16,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00]])

In [39]:
A = np.matrix('2,0,0; 0,4,0; 0,0,5')
A
B=np.linalg.inv(A)
B
#C=A*B
#C
print(np.linalg.det(A))

39.99999999999998


In [38]:
import numpy as np
A = np.matrix ("1, 2, 3; 4, 5, 6 ; 7, 8, 10")
print(np.linalg.det(A))
# -3.0000000000009

-2.9999999999999996


In [41]:
import numpy as np
A = np.matrix ("1, 2, ; 1, 1")
B = np.matrix ("5,,-2; -1, 4")
print(round(np.linalg.det(A)))
print(round(np.linalg.det(B)))
print(round(np.linalg.det(A+B)))

-1
18
30


Задание 8.8

2 points possible (graded)

In [43]:
import numpy as np
A = np.matrix ("2,0,0; 0,1,0 ;0,0,4")
B=np.linalg.inv(A)
print(round(np.linalg.det(A)))
print(round((np.linalg.det(B)),3))

8
0.125
